package neton.ksp

import com.google.devtools.ksp.processing.*
import com.google.devtools.ksp.symbol.*
import java.io.OutputStreamWriter

private val APP_MODULE_ID_PATTERN = Regex("^[a-z][a-z0-9-]*$")

/**
 * Application 模块聚合处理器（MANIFEST-P2）。
 *
 * 读取 application 编译单元的 KSP 选项 `neton.modules`（逗号分隔模块 id 列表），
 * 对每个 id 按优先级探测模块入口（编译期 resolver，跨 klib）：
 *
 * 1. `neton.module.{id}.generated.{Id}ModuleManifest` — @Module manifest 化的模块
 * 2. `init.{Id}ModuleInitializer` — 手写 initializer 的兼容模块
 *
 * 两者都不存在 → 编译错误（拼错 id / 忘加依赖在编译期暴露，不是启动期）。
 *
 * 生成 `neton.application.generated.GeneratedApplicationModules`：
 * ```kotlin
 * object GeneratedApplicationModules {
 *     val modules: List<ModuleInitializer> = listOf(...)
 * }
 * ```
 *
 * Main.kt 的 migrate 子命令 / startup precheck / serve modules(...) 三处共用这一份，
 * 模块列表唯一来源是 build.gradle.kts 的 ksp arg —— 引入模块 = dependency 一行 +
 * ksp arg 加一个 id。列表顺序保持声明顺序（Neton.run 内部仍有 dependsOn 拓扑排序兜底）。
 *
 * 未配置 `neton.modules` 时不生成任何代码（模块编译单元零影响 —— 模块自己的 KSP
 * 跑的是 ControllerProcessor/LogicProcessor 等，不会带这个 arg）。
 */
class ApplicationRegistryProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
    private val options: Map<String, String>
) : SymbolProcessor {

    private var invoked = false

    override fun process(resolver: Resolver): List<KSAnnotated> {
        if (invoked) return emptyList()
        invoked = true

        val modulesArg = options["neton.modules"]?.takeIf { it.isNotBlank() } ?: return emptyList()
        val ids = modulesArg.split(',').map { it.trim() }.filter { it.isNotEmpty() }
        if (ids.isEmpty()) return emptyList()

        val refs = mutableListOf<Pair<String, String>>()  // id to FQN
        for (id in ids) {
            if (!APP_MODULE_ID_PATTERN.matches(id)) {
                logger.error(
                    "neton.modules entry '$id' is invalid. " +
                            "Must match [a-z][a-z0-9-]* (lowercase, start with letter)."
                )
                return emptyList()
            }
            val pascal = id.split('-', '_').joinToString("") { part ->
                part.replaceFirstChar { it.uppercaseChar() }
            }
            val manifestFqn = "neton.module.$id.generated.${pascal}ModuleManifest"
            val legacyFqn = "init.${pascal}ModuleInitializer"
            val fqn = when {
                resolver.getClassDeclarationByName(resolver.getKSNameFromString(manifestFqn)) != null ->
                    manifestFqn
                resolver.getClassDeclarationByName(resolver.getKSNameFromString(legacyFqn)) != null ->
                    legacyFqn
                else -> {
                    logger.error(
                        "neton.modules entry '$id': neither $manifestFqn (manifest mode) nor " +
                                "$legacyFqn (legacy hand-written initializer) found on the classpath. " +
                                "Check the module id spelling and the gradle dependency."
                    )
                    return emptyList()
                }
            }
            refs.add(id to fqn)
        }

        val dependencies = Dependencies(
            aggregating = true,
            *resolver.getAllFiles().toList().toTypedArray()
        )
        generateRegistry(refs, dependencies)
        return emptyList()
    }

    private fun generateRegistry(refs: List<Pair<String, String>>, dependencies: Dependencies) {
        val pkg = "neton.application.generated"
        val className = "GeneratedApplicationModules"

        val file = codeGenerator.createNewFile(
            dependencies = dependencies,
            packageName = pkg,
            fileName = className
        )

        OutputStreamWriter(file).use { w ->
            w.write("// AUTO-GENERATED by Neton KSP ApplicationRegistryProcessor - DO NOT EDIT\n")
            w.write("package $pkg\n\n")
            w.write("import neton.core.module.ModuleInitializer\n\n")
            w.write("/**\n")
            w.write(" * Application 模块 registry（MANIFEST-P2）。\n")
            w.write(" *\n")
            w.write(" * 唯一来源: build.gradle.kts 的 `ksp { arg(\"neton.modules\", \"...\") }`。\n")
            w.write(" * migrate 子命令 / startup precheck / serve modules(...) 共用这一份。\n")
            w.write(" * 顺序 = 声明顺序; Neton.run 内部仍按 dependsOn 拓扑排序兜底。\n")
            w.write(" */\n")
            w.write("object $className {\n\n")
            w.write("    val modules: List<ModuleInitializer> = listOf(\n")
            refs.forEach { (id, fqn) ->
                w.write("        $fqn,  // $id\n")
            }
            w.write("    )\n")
            w.write("}\n")
        }

        logger.info(
            "Generated $pkg.$className with ${refs.size} module(s): " +
                    refs.joinToString { (id, fqn) ->
                        "$id=${if (fqn.contains(".generated.")) "manifest" else "legacy"}"
                    }
        )
    }
}

class ApplicationRegistryProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor {
        return ApplicationRegistryProcessor(
            environment.codeGenerator,
            environment.logger,
            environment.options
        )
    }
}
