package neton.ksp

import com.google.devtools.ksp.processing.*
import com.google.devtools.ksp.symbol.*
import java.io.OutputStreamWriter

private data class ConfigEntry(val component: String, val order: Int, val clazz: KSClassDeclaration)

/**
 * 扫描 @NetonConfig(component, order) 并生成 security configurer 装配代码。
 *
 * # 两种模式
 *
 * **模块模式（neton.moduleId 存在）**：每个模块把自己的 @NetonConfig("security") 收集成一个
 * **编译期可探测的贡献对象** `neton.module.{id}.generated.{Id}SecurityConfigContribution`，
 * 暴露 `securityConfigurers: List<NetonConfigurer<SecurityBuilder>>`。
 *
 * **应用模式（neton.moduleId 不存在）**：生成 `neton.core.generated.GeneratedNetonConfigRegistry`，
 * 把本编译单元的 @NetonConfig + （若设了 `neton.modules`）各模块的 SecurityConfigContribution
 * **聚合**成单个 registry。Main.kt 用 `configRegistry(GeneratedNetonConfigRegistry)` 在组件 start
 * 前绑定，SecurityComponent.start 再 `sortedBy{order}` 应用。
 *
 * # 为什么是编译期聚合而不是 runtime bind
 *
 * `SecurityComponent.start` 跑在 module init **之前**，所以模块在 init 阶段 bind configurer 来不及
 * 生效。configurer 必须在 app 编译期就聚合进 registry、随 DSL 早绑定。这与 MANIFEST-P2 的
 * [ApplicationRegistryProcessor] 探测 per-module manifest 完全同构（跨 klib 编译期 resolve）。
 */
class NetonConfigProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
    private val options: Map<String, String> = emptyMap()
) : SymbolProcessor {

    private val moduleId: String? = options["neton.moduleId"]?.takeIf { it.isNotBlank() }
    private val modulesArg: String? = options["neton.modules"]?.takeIf { it.isNotBlank() }
    private val netonConfigAnnotationName = "neton.core.config.NetonConfig"

    private var invoked = false

    override fun process(resolver: Resolver): List<KSAnnotated> {
        if (invoked) return emptyList()

        val symbols = resolver.getSymbolsWithAnnotation(netonConfigAnnotationName)
        val configClasses = symbols.filterIsInstance<KSClassDeclaration>().toList()

        val grouped = configClasses.mapNotNull { clazz ->
            val ann =
                clazz.annotations.firstOrNull { it.shortName.asString() == "NetonConfig" } ?: return@mapNotNull null
            val component =
                ann.arguments.find { it.name?.asString() == "component" }?.value as? String ?: return@mapNotNull null
            val order = ann.arguments.find { it.name?.asString() == "order" }?.value as? Int ?: 0
            ConfigEntry(component, order, clazz)
        }.groupBy({ it.component }, { it })

        val securityEntries = grouped["security"]?.toList() ?: emptyList()

        if (moduleId != null) {
            // 模块模式：本模块有 security configurer 才生成贡献对象（无则零产物）。
            if (securityEntries.isNotEmpty()) {
                invoked = true
                logger.info("NetonConfig[$moduleId]: ${securityEntries.size} security configurer(s) → contribution")
                generateModuleContribution(moduleId, securityEntries)
            }
        } else {
            // 应用模式：本地 configurer 或 neton.modules 任一存在就生成聚合 registry。
            if (securityEntries.isNotEmpty() || modulesArg != null) {
                invoked = true
                val contributions = resolveModuleContributions(resolver)
                logger.info(
                    "NetonConfig[app]: ${securityEntries.size} local + ${contributions.size} module " +
                            "security contribution(s) → GeneratedNetonConfigRegistry"
                )
                generateConfigRegistry(securityEntries, contributions)
            }
        }

        return emptyList()
    }

    // ---------- 模块模式：编译期贡献对象 ----------

    /** 生成 `neton.module.{id}.generated.{Id}SecurityConfigContribution`（app 编译期探测）。 */
    private fun generateModuleContribution(moduleId: String, securityEntries: List<ConfigEntry>) {
        val pkg = "neton.module.$moduleId.generated"
        val className = "${moduleId.toPascal()}SecurityConfigContribution"

        val file = codeGenerator.createNewFile(
            dependencies = Dependencies(true, *securityEntries.mapNotNull { it.clazz.containingFile }.toTypedArray()),
            packageName = pkg,
            fileName = className
        )

        OutputStreamWriter(file).use { w ->
            w.write("// AUTO-GENERATED by Neton KSP NetonConfigProcessor - DO NOT EDIT\n")
            w.write("package $pkg\n\n")
            w.write("import neton.core.config.NetonConfigurer\n")
            w.write("import neton.core.config.NetonConfigurers\n")
            w.write("import neton.core.interfaces.SecurityBuilder\n")
            securityEntries.forEach { w.write("import ${it.clazz.qualifiedName!!.asString()}\n") }
            w.write("\n")
            w.write("/**\n")
            w.write(" * 模块 [$moduleId] 的 security configurer 贡献（${securityEntries.size} 个）。\n")
            w.write(" * 由 app 编译期 NetonConfigProcessor 探测并聚合进 GeneratedNetonConfigRegistry。\n")
            w.write(" */\n")
            w.write("object $className {\n")
            w.write("    val securityConfigurers: List<NetonConfigurer<SecurityBuilder>> = listOf(\n")
            securityEntries.forEach {
                w.write("        NetonConfigurers.ordered(${it.order}, ${it.clazz.simpleName.asString()}()),\n")
            }
            w.write("    )\n")
            w.write("}\n")
        }
    }

    // ---------- 应用模式：跨模块探测 + 聚合 registry ----------

    /**
     * 按 `neton.modules` 列表探测各模块的 SecurityConfigContribution（编译期 resolve，跨 klib）。
     * 大多数模块没有 security configurer → 探测不到属正常，静默跳过（与 ApplicationRegistryProcessor
     * 的「每个模块必须有 manifest」不同 —— 那里缺失是 error）。返回探测到的 contribution FQN 列表。
     */
    private fun resolveModuleContributions(resolver: Resolver): List<String> {
        val arg = modulesArg ?: return emptyList()
        val ids = arg.split(',').map { it.trim() }.filter { it.isNotEmpty() }
        val found = mutableListOf<String>()
        for (id in ids) {
            val pascal = id.toPascal()
            val fqn = "neton.module.$id.generated.${pascal}SecurityConfigContribution"
            if (resolver.getClassDeclarationByName(resolver.getKSNameFromString(fqn)) != null) {
                found.add(fqn)
            }
        }
        return found
    }

    /** 生成聚合 registry：本地 @NetonConfig + 各模块 contribution。 */
    private fun generateConfigRegistry(localEntries: List<ConfigEntry>, contributionFqns: List<String>) {
        val file = codeGenerator.createNewFile(
            dependencies = Dependencies(true, *localEntries.mapNotNull { it.clazz.containingFile }.toTypedArray()),
            packageName = "neton.core.generated",
            fileName = "GeneratedNetonConfigRegistry"
        )

        OutputStreamWriter(file).use { w ->
            w.write("// AUTO-GENERATED by Neton KSP NetonConfigProcessor - DO NOT EDIT\n")
            w.write("package neton.core.generated\n\n")
            w.write("import neton.core.config.NetonConfigurer\n")
            w.write("import neton.core.config.NetonConfigRegistry\n")
            w.write("import neton.core.config.NetonConfigurers\n")
            w.write("import neton.core.interfaces.SecurityBuilder\n")
            localEntries.forEach { w.write("import ${it.clazz.qualifiedName!!.asString()}\n") }
            w.write("\n")
            w.write("/**\n")
            w.write(" * 聚合 security config registry：本地 ${localEntries.size} + 模块 ${contributionFqns.size} 个贡献。\n")
            w.write(" * order 在 SecurityComponent.start 消费时统一 sortedBy 应用。\n")
            w.write(" */\n")
            w.write("object GeneratedNetonConfigRegistry : NetonConfigRegistry {\n\n")
            w.write("    override val securityConfigurers: List<NetonConfigurer<SecurityBuilder>> =\n")

            // 本地 configurer（直接构造 + ordered 包装）
            if (localEntries.isEmpty()) {
                w.write("        emptyList<NetonConfigurer<SecurityBuilder>>()")
            } else {
                w.write("        listOf(\n")
                localEntries.forEach {
                    w.write("            NetonConfigurers.ordered(${it.order}, ${it.clazz.simpleName.asString()}()),\n")
                }
                w.write("        )")
            }
            // 拼接各模块贡献
            contributionFqns.forEach { fqn ->
                w.write(" +\n        $fqn.securityConfigurers")
            }
            w.write("\n}\n")
        }
    }

    private fun String.toPascal(): String =
        split('-', '_').joinToString("") { part -> part.replaceFirstChar { it.uppercaseChar() } }
}

class NetonConfigProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor {
        return NetonConfigProcessor(environment.codeGenerator, environment.logger, environment.options)
    }
}
