/*
 * Shared Gradle script — register `generateMigrationResources` task in a module.
 *
 * Reads `sql/<dialect>/V<ver>__<desc>.sql`,生成
 * `build/generated/migration/init/generated/<PascalId>MigrationResources.kt`,
 * 内含 `MigrationSource` 单例,SQL 内容 Base64 + 编译期解码,checksum 编译期 SHA-256。
 *
 * 使用:
 *   apply(from = "../../neton/scripts/embed-migration-resources.gradle.kts")
 *   extra["neton.migration.moduleId"] = "member"
 *   extra["neton.migration.dialects"] = listOf("postgresql")
 *
 * 模块 ModuleInitializer.migrations() 引用 generated `<PascalId>MigrationResources.sources`。
 */

import java.security.MessageDigest
import java.util.Base64

val moduleId = (extra["neton.migration.moduleId"] as? String)
    ?: error("module must set extra[\"neton.migration.moduleId\"] before applying embed-migration-resources")
@Suppress("UNCHECKED_CAST")
val dialects = (extra["neton.migration.dialects"] as? List<String>) ?: listOf("postgresql")
val sqlSourceDir = (extra["neton.migration.sqlSourceDir"] as? File) ?: file("sql")

val pascalId = moduleId.split('-', '_', '.').joinToString("") { p -> p.replaceFirstChar { it.uppercaseChar() } }
val className = "${pascalId}MigrationResources"
val pkg = "init.generated"
val genRoot = layout.buildDirectory.dir("generated/migration/kotlin")
val genFile = genRoot.map { it.file("init/generated/$className.kt") }

val sqlInputs = files(dialects.map { File(sqlSourceDir, it) })

val generateMigrationResources by tasks.registering {
    group = "neton-migration"
    description = "Generate $pascalId$className.kt with embedded SQL constants."

    inputs.files(sqlInputs).withPropertyName("sqlSources").skipWhenEmpty()
    outputs.file(genFile)

    doLast {
        val out = genFile.get().asFile
        out.parentFile.mkdirs()

        val nameRegex = Regex("""^V(\d+)__([a-z0-9_]+)\.sql$""")

        // 收集 (dialect → 按 version 升序的脚本列表)
        val perDialect = linkedMapOf<String, List<Triple<String, String, String>>>() // dialect → [(version, desc, content)]
        for (dialect in dialects) {
            val dir = File(sqlSourceDir, dialect)
            if (!dir.isDirectory) {
                perDialect[dialect] = emptyList()
                continue
            }
            val files = dir.listFiles { f -> f.name.endsWith(".sql") }?.toList().orEmpty()
            val scripts = files.mapNotNull { f ->
                val m = nameRegex.matchEntire(f.name) ?: return@mapNotNull null
                Triple(m.groupValues[1], m.groupValues[2], f.readText())
            }.sortedBy { it.first.padStart(8, '0') }
            // duplicate version 早失败
            val dupes = scripts.groupBy { it.first }.filter { it.value.size > 1 }.keys
            if (dupes.isNotEmpty()) error("[$moduleId/$dialect] duplicate versions: $dupes")
            perDialect[dialect] = scripts
        }

        out.writer().use { w ->
            w.write("// AUTO-GENERATED by generateMigrationResources — DO NOT EDIT.\n")
            w.write("package $pkg\n\n")
            w.write("import neton.core.module.MigrationDialect\n")
            w.write("import neton.core.module.MigrationScript\n")
            w.write("import neton.core.module.MigrationSource\n")
            w.write("import kotlin.io.encoding.Base64\n")
            w.write("import kotlin.io.encoding.ExperimentalEncodingApi\n\n")

            w.write("@OptIn(ExperimentalEncodingApi::class)\n")
            w.write("private fun b64(s: String): String = Base64.decode(s).decodeToString()\n\n")

            w.write("/**\n")
            w.write(" * Embedded migration sources for module `$moduleId`.\n")
            w.write(" * Generated from `sql/<dialect>/V*.sql` at build time.\n")
            w.write(" */\n")
            w.write("object $className {\n")
            w.write("    val sources: List<MigrationSource> = listOf(\n")

            for ((dialect, scripts) in perDialect) {
                if (scripts.isEmpty()) continue
                val dialectEnum = when (dialect) {
                    "postgresql" -> "POSTGRESQL"
                    "mysql" -> "MYSQL"
                    "sqlite" -> "SQLITE"
                    else -> error("unknown dialect: $dialect")
                }
                w.write("        MigrationSource(\n")
                w.write("            moduleId = \"$moduleId\",\n")
                w.write("            dialect = MigrationDialect.$dialectEnum,\n")
                w.write("            scripts = listOf(\n")
                for ((version, desc, content) in scripts) {
                    val bytes = content.toByteArray(Charsets.UTF_8)
                    val checksum = sha256Hex(bytes)
                    val base64 = Base64.getEncoder().encodeToString(bytes)
                    w.write("                MigrationScript(\n")
                    w.write("                    version = \"$version\",\n")
                    w.write("                    description = \"$desc\",\n")
                    w.write("                    content = b64(\"$base64\"),\n")
                    w.write("                    checksum = \"$checksum\",\n")
                    w.write("                ),\n")
                }
                w.write("            ),\n")
                w.write("        ),\n")
            }

            w.write("    )\n")
            w.write("}\n")
        }

        logger.lifecycle("generated $out")
    }
}

// 把 generated 目录加进 commonMain 源集(用 reflection 避免 plugin classpath 依赖)
extensions.findByName("kotlin")?.let { ext ->
    val sourceSets = ext.javaClass.getMethod("getSourceSets").invoke(ext)
    val commonMain = sourceSets.javaClass.getMethod("getByName", String::class.java)
        .invoke(sourceSets, "commonMain")
    val kotlinSrcDirs = commonMain.javaClass.methods.first { it.name == "getKotlin" }.invoke(commonMain)
    kotlinSrcDirs.javaClass.getMethod("srcDir", Any::class.java).invoke(kotlinSrcDirs, genRoot.get().asFile)
}

// 让 Kotlin 编译依赖此 task
tasks.matching {
    it.name.startsWith("compileKotlin") ||
        it.name.startsWith("compileCommonMainKotlinMetadata") ||
        it.name.startsWith("kspKotlin")
}.configureEach {
    dependsOn(generateMigrationResources)
}

fun sha256Hex(bytes: ByteArray): String {
    val md = MessageDigest.getInstance("SHA-256")
    val d = md.digest(bytes)
    val sb = StringBuilder(d.size * 2)
    for (b in d) {
        val v = b.toInt() and 0xff
        sb.append("0123456789abcdef"[v ushr 4])
        sb.append("0123456789abcdef"[v and 0xf])
    }
    return sb.toString()
}
